### ISSUE TITLE
[Example] Placing Pentominoes into 2D Array

### ISSUE THREAD

**Issue by kenofori** [taylorjg/DlxLib#5]
Hi there,

Thank you very much for creating this library. Is there an example of filling a 2D Array with Pentominoes just like in the paper that returns all the possible solutions?

<img width="193" alt="Screenshot 2019-05-11 at 1 21 39 PM" src="https://user-images.githubusercontent.com/30837872/57567244-c326f900-73ef-11e9-907f-b7ccb1e67dca.png">

Thanks

**Comment by taylorjg** [comment]
No - but it's a good idea. So, I am currently working on a little web app to do it. It's not quite finished yet. But you can see the progress [here](https://github.com/taylorjg/pentominoes).

**Comment by kenofori** [comment]
Yes, its looks great and thats what im trying to do in C# with your lib.
Can u plz guide how can i do that in case a C# implementation is not coming soon so i can try it.

**Comment by taylorjg** [comment]
Well, my day job has been Scala and JavaScript for the last 3 years. So I thought it would be a useful exercise for me to re-familiarise myself with C#. Check out [pentominoes-cs](https://github.com/taylorjg/pentominoes-cs). It is a .NET Core console app. I am on a MacBook these days so I can't do a WFP app. I hope you find it useful.

**Comment by kenofori** [comment]
Console is Way Better because then its easier to understand it without  side tracked due to WFP. Thank you very much, :D
