### ISSUE TITLE
Solution - Not an issue with the program

### ISSUE THREAD

**Issue by KyeScoble** [taylorjg/DlxLib#6]
Does anyone have the solution to the chess board puzzle. I cant run the program and have had the chess puzzle forever now and this is the only online resource ive found close to solving it.

**Comment by taylorjg** [comment]
I can't run the program either because I don't have a Windows machine any longer.

If I find some time, I'll try to make a command line version of the program and run it on .NET Core and post one of the solutions here (there are multiple solutions).

**Comment by taylorjg** [comment]
I think this is what you are looking for:

```
GDDMKKCC
GGDMMKKC
AGDDMHKI
AEEEMHHI
AANEEHII
AFNNNNBI
LFFFBBBJ
LLLFJJJJ
```

**Comment by taylorjg** [comment]
This format might be easier to read:

```
┏━━━┳━━━━━━━┳━━━┳━━━━━━━┳━━━━━━━┓
┃ G ┃ D   D ┃ M ┃ K   K ┃ C   C ┃
┃   ┗━━━┓   ┃   ┗━━━┓   ┗━━━┓   ┃
┃ G   G ┃ D ┃ M   M ┃ K   K ┃ C ┃
┣━━━┓   ┃   ┗━━━┓   ┣━━━┓   ┣━━━┫
┃ A ┃ G ┃ D   D ┃ M ┃ H ┃ K ┃ I ┃
┃   ┣━━━┻━━━━━━━┫   ┃   ┗━━━┫   ┃
┃ A ┃ E   E   E ┃ M ┃ H   H ┃ I ┃
┃   ┗━━━┳━━━┓   ┗━━━┫   ┏━━━┛   ┃
┃ A   A ┃ N ┃ E   E ┃ H ┃ I   I ┃
┃   ┏━━━┫   ┗━━━━━━━┻━━━╋━━━┓   ┃
┃ A ┃ F ┃ N   N   N   N ┃ B ┃ I ┃
┣━━━┫   ┗━━━━━━━┳━━━━━━━┛   ┣━━━┫
┃ L ┃ F   F   F ┃ B   B   B ┃ J ┃
┃   ┗━━━━━━━┓   ┣━━━━━━━━━━━┛   ┃
┃ L   L   L ┃ F ┃ J   J   J   J ┃
┗━━━━━━━━━━━┻━━━┻━━━━━━━━━━━━━━━┛
```

**Comment by taylorjg** [comment]
@KyeScoble Hi - have I answered your question ? If so, I'll close this issue.

----

In case anyone is interested, here is a link to the repo containing the code used to find and print the above solution. It is a re-working of the [DlxLibDemo3](https://github.com/taylorjg/DlxLib/tree/master/DlxLibDemo3) project.

https://github.com/taylorjg/DraughtboardPuzzleConsole
